### PR TITLE
Automatically publish new chart versions Github pages

### LINKED ISSUE #6: Helm Chart Release
We need a Release with GH Actions:

https://github.com/helm/chart-releaser-action

### PR DESCRIPTION
**Pull request by jacksgt**
Create a GH Action worklfow that uses "chart-releaser-action" to build
the Helm charts if changes are detected and push the artifacts onto
the gh-pages branch.

>  It does this – during every push to master – by checking each chart in your project, and whenever there's a new chart version, creates a corresponding GitHub release named for the chart version, adds Helm chart artifacts to the release, and creates or updates an index.yaml file with metadata about those releases, which is then hosted on GitHub Pages

https://github.com/helm/chart-releaser-action

Fixes #6

### CODE REVIEW

**Comment by jacksgt** [comment]
@martialblog Could you work your Github admin magic again to add the "GITHUB_TOKEN" to secrets?

**Comment by martialblog** [comment]
What rights does the token need?

**Comment by jacksgt** [comment]
I think you need to create a Deploy token with "Allow write access" and add that to the secrets.

**Comment by mueller-ma** [comment]
No need to create this token:

> GitHub automatically creates a GITHUB_TOKEN secret to use in your workflow. 

https://docs.github.com/en/actions/reference/authentication-in-a-workflow

**Review by martialblog — APPROVED** [review]
:shipit:

**Comment by jacksgt** [comment]
Meeeh.

https://github.com/helm/chart-releaser-action/issues/87

**Pull request merged**
